# Generated by Django 3.1.5 on 2021-01-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=15)),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
